# ===============================
# API / Mail / Custom Keys
# ===============================
apiKey=${BREVO_API_KEY}
genKey=${GEMINI_API_KEY}

# ===============================
# OAuth2 Client Credentials (Google)
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# Adzuna Credentials
# ===============================
application-id=${ADZUNA_APP_ID}
application-api-key=${ADZUNA_API_KEY}

# ===============================
# JWT Credentials
# ===============================
jwt-key=${JWT_SECRET_KEY}

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
