package com.ai.Resume.analyser.model;

public enum CandidateStatus {
    NEW, PREVIOUS_APPLICANT, REJECTED, HOLD, CONTACTED, INTERESTED,
    NOT_INTERESTED, NO_RESPONSE, ACTIVE_ENGAGEMENT, SHORTLISTED, INTERVIEW, HIRED
}
