package com.ai.Resume.analyser.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;

/**
 * TalentRevive's rediscoverable candidate pool. One row per registered
 * job-seeker (keyed by the same email as usersTable), populated/refreshed
 * whenever they run a resume analysis via the existing appService.extract().
 *
 * Previous draft of this entity used an autogenerated id and a single jobId
 * FK, which tied a "candidate" to one job posting and had no resume content
 * or experience data - meaning there was nothing for Stage 1 hard-filtering
 * or Stage 2 AI matching to work with, and no rediscovery across jobs was
 * possible. Rebuilt keyed by email so one profile can be matched against
 * any number of job postings.
 */
@Data
@Entity
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Candidate {

    @Id
    private String email;

    private String name;

    @Lob
    @Column(length = 20000)
    private String resumeText;

    private int experienceYears;

    // Free-text roles the candidate targeted at analysis time (from the
    // existing "roles" form field) - not a hard filter, just context for HR.
    private String targetRoles;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private CandidateStatus status = CandidateStatus.NEW;

    @Builder.Default
    private boolean doNotContact = false;

    @CreationTimestamp
    @Column(updatable = false)
    private Date createdAt;

    @UpdateTimestamp
    private Date updatedAt;
}
